version: "3"

services:
  ansible:
    container_name: ansible
    build: "./controller"
    volumes:
      - "./controller/ansible:/ansible"
    networks:
      - default

  target:
    container_name: target
    build: ./target
    networks:
      - default
    ports:
      - 22:22

networks:
  default:
    driver: bridge
